DROP TABLE IF EXISTS CURRENCY;

CREATE TABLE CURRENCY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(3) NOT NULL UNIQUE, -- 幣別代碼，如 USD, GBP
    CHINESE_NAME VARCHAR(50) NOT NULL -- 幣別中文名稱，如 美金, 英鎊
);